language: python
python: 3.5
script:
 - pip install pip -U
 - pip install -r requirements.txt
 - pelican
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output/
  target_branch: master
  on:
branch: sources